var lang = XT.stringsFor("en_US", {
    "_authURI": "Auth URI",
    "_clientType": "Client Type",
    "_delegatedAccess": "Delegated Access",
    "_id": "ID",
    "_issued": "Issued",
    "_logo": "Logo",
    "_maintainOauth2clients": "Maintain OAUTH2 Clients",
    "_oauth2": "OAUTH2",
    "_oauth2Client": "OAUTH2 Client",
    "_oauth2Clients": "OAUTH2 Clients",
    "_redirects": "Redirects",
    "_redirectURI": "Redirect URI",
    "_secret": "Secret",
    "_serviceAccount": "Service Account",
    "_tokenURI": "Token URI",
    "_webServer": "Web Server",
    "_website": "Website",
    "_x509PubCert": "X.509 Public Key Certificate"
});
